export const category_names: Resource[] = [
  $r('app.string.category_1'),
  $r('app.string.category_2'),
  $r('app.string.category_3'),
  $r('app.string.category_4'),
  $r('app.string.category_5'),
  $r('app.string.category_6')
];

export const categories: string[] = [
  'Imagination & Creativity',
  'Emotions & Inner Feelings',
  'Relationships & Love',
  'Decision & Adventure',
  'Fear & Subconscious Mind',
  'Self-Discovery & Dreams'
];
